### PR TITLE
Documentation Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

Draft ➞ WIP ➞ Changes will change

<br>
<br>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `remote`

  <br>

<br>
<br>

## ![Badge Changes]

- Formatted badges

- Added quicklinks

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***,
  *please first let me know about them, before disregarding it entirely so*
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Info]

If you want to know more about **Markdown** check out:

<br>

                            [![Button MarkedDown]][MarkedDown]

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Arduino-IRremote

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@ArminJo Check here for progress~

**Comment by ArminJo** [comment]
Quick feedback.

- Some section spacings are great, others no so useful.
- Using aligning in tables is also useful.
- The upper badges lack functionality and are more complicated than the existing ones.
- Using keys for protocol list is a nice Idea!

Just my 5 cent.
I have to leave my PC now...

**Comment by ElectronicsArchiver** [comment]
@ArminJo Btw, I would of course prefer to do this in multiple smaller PRs.

**Review by samuelbarrionuevo — APPROVED** [review]

**Comment by ElectronicsArchiver** [comment]
@ArminJo 

> Btw, I would of course prefer to do this in multiple smaller PRs.

In fact I will not continue in any other way.

I just had to manually 'fix' about 30 conflict while rebasing.

Oh isn't having a giant README just the best, makes life so
much EASIER when other people work on the same content.

I will leave this PR at the current changes.

**Comment by ArminJo** [comment]
@ElectronicsArchiver Thanks a lot for all your work an ideas 🥇 
I took many, as you can easily see 😀 and added you to the list of contibutors 👍 .

**Pull request closed without merging**
