### PR TITLE
Update decodeRC5() to handle extended RC5

### PR DESCRIPTION
**Pull request by leres**
I used this page for reference:  [http://www.pcbheaven.com/userpages/The_Philips_RC5_Protocol/](http://www.pcbheaven.com/userpages/The_Philips_RC5_Protocol/)

For testing I used XDPR2 (Siriusxm v2.0) and SWWBR1 (Siriusxm Tour) remotes; the only difference between them are the button labels (i.e. they send the same codes).

### CODE REVIEW

**Comment by ArminJo** [comment]
Hi,
the new RC5 decode and send functions (enable USE_STANDARD_DECODE on line 34 of IRremote.h) should support RC5Ext natively.
Please test it and report if something is missing.

**Comment by leres** [comment]
> Hi,
> the new RC5 decode and send functions (enable USE_STANDARD_DECODE on line 34 of IRremote.h) should support RC5Ext natively.
> Please test it and report if something is missing.

Wow! Upgrading from 2.8.1 to 2.9.0 I'm finding many backwards incompatible changes; it's going to take some effort to get my code working with this version. It also looks like the bss footprint has increased (by 16 byttes), it's already challenging to write a sketch that does ir decoding and also run a display.

**Comment by ArminJo** [comment]
The current Repo is version 3.0 😀 
Are the 16 bytes a problem? Most of them are for legacy compatibility and support of the repeat decoding.
If you can do me a favor and specify the incompatibilities, I can try to document them, together with the ones I found, in the Readme.
Thanks!

**Comment by leres** [comment]
> The current Repo is version 3.0 grinning
> Are the 16 bytes a problem? Most of them are for legacy compatibility and support of the repeat decoding.
> If you can do me a favor and specify the incompatibilities, I can try to document them, together with the ones I found, in the Readme.
> Thanks!

I see what happened; I was building against a git checkout of 3.X instead of 2.9.0. My bad...

**Pull request closed without merging**
