### PR TITLE
New configuration and API

### PR DESCRIPTION
**Pull request by DrDiettrich**
Added the standard Stream API with methods begin(), available() and read().
It's no more required to edit the library for using a specific decoder only.

### CODE REVIEW

**Comment by z3t0** [comment]
Would it be possible to explain the changes in a short explanation? Haha it just seems like a lot to go over. Thanks!

**Comment by DrDiettrich** [comment]
Rafi Khan schrieb:
> Would it be possible to explain the changes in a short explanation?

The short explanations are in the commits.

I'm not familiar with the git procedures, perhaps you have to create a 
local copy of my repository in order to follow all the steps I took?

The bigger steps are:
- make all decoders public
- move decoder_results into IRrecv (out of argument lists)
- add new API methods

DoDi

**Comment by z3t0** [comment]
Thanks I will look through the commits, and dont worry I dont think anyone really knows how to use git besides commit and push :smile:

**Comment by DrDiettrich** [comment]
Rafi Khan schrieb:
> Thanks I will look through the commits

Feel free to ask more specific questions. I can create a new branch for 
implementing something according to your needs/expectations. Or you give 
me write access to a branch in your repository...

**Comment by z3t0** [comment]
I'm a bit confused why we would want to remove the defines for the protocols.

**Comment by ArminJo** [comment]
Thanks for the inspiration

**Pull request closed without merging**
