### PR TITLE
Fix Sony 20 bit decoding (return the number of bits decoded)

### PR DESCRIPTION
**Pull request by leres**
Testing done with a Sony Cybershot RMT-DSC1 remote

### CODE REVIEW

**Comment by leres** [comment]
I just found a Sony RM-X201 remote that sends 15 bit codes.

**Comment by ArminJo** [comment]
You expect more than 255 bits for Sony???

**Comment by leres** [comment]
> You expect more than 255 bits for Sony???

I assume you're referring to:

    `uint16_t bits = 0;^M`

I made it the same size as the bits member in the decode_results struct.

While the nbits argument to IRsend::sendNEC() and IRsend::sendRC6 are uint8_t, all others are int (16 bits). Local bits/nbits variables in irPronto.cpp, ir_RC5_RC6.cpp, and ir_Sharp_alt.cpp are all 16 bit (either unsigned int or uint16_t).

**Comment by ArminJo** [comment]
Thanks!
I haven't payed attention to this, I am going to change it glabally after the merge.

**Pull request merged**
