### PR TITLE
Feature/update around printing pronto

### PR DESCRIPTION
**Pull request by asukiaaa**
- Apply size_t to compensateAndDumpSequence for String
- Start prontoData with lower case

### CODE REVIEW

**Comment by ArminJo** [comment]
I will wait a few days to collect all changes if it is OK for you.

**Comment by asukiaaa** [comment]
Thank you for checking.

When I write
```cpp
#define RAW_BUFFER_LENGTH 400
#include <IRremote.h>
```
on ReceiveDump example, RAW_BUFFER_LENGTH is not included on ir_Pronto.cpp and for loop does not stop because length type is still uint8 but number is larger than 255.

If I change ir_Pronto.cpp to ir_Pront.hpp and include it on IRremote.hpp, it works as I expect.

How about this change?

**Comment by ArminJo** [comment]
> ```c++
> #define RAW_BUFFER_LENGTH 400
> #include <IRremote.h>
> ```

This is NOT possible as you have discovered. :-( See [documentation](https://github.com/Arduino-IRremote/Arduino-IRremote#compile-options--macros-for-this-library).
What is the use case of using such a huge rawbuffer?

**Comment by asukiaaa** [comment]
> This is NOT possible as you have discovered, as long as not all decoders are converted to hpp. 

I could but does this mean that you don't want to do?

I require about 300 buffer length to decode remote controller for air conditioner made by toshiba.

https://www.yodobashi.com/community/product/100000001002279254/index.html

```
Raw result in internal ticks (50 us) - with leading gap
rawData[296]: 
     -36577
     +  89,-  88     +  11,-  32     +  11,-  32     +  11,-  33
     +  10,-  33     +  11,-  11     +  10,-  12     +  10,-  33
     +  11,-  11     +  11,-  10     +  11,-  11     +  11,-  11
     +  11,-  10     +  11,-  33     +  11,-  32     +  11,-  11
     +  10,-  33     +  11,-  11     +  10,-  12     +  10,-  11
     +  11,-  11     +  10,-  12     +  10,-  11     +  11,-  33
     +  10,-  33     +  11,-  32     +  11,-  32     +  11,-  33
     +  11,-  33     +  10,-  33     +  11,-  32     +  11,-  11
     +  11,-  11     +  10,-  12     +  10,-  11     +  11,-  11
     +  10,-  12     +  10,-  11     +  11,-  11     +  10,-  12
     +  10,-  33     +  10,-  33     +  11,-  11     +  10,-  12
     +  10,-  11     +  11,-  11     +  11,-  11     +  10,-  12
     +  10,-  11     +  11,-  11     +  10,-  11     +  11,-  11
     +  11,-  11     +  10,-  11     +  11,-  11     +  11,-  11
     +  11,-  32     +  11,-  11     +  10,-  12     +  10,-  11
     +  11,-  11     +  11,-  11     +  10,-  11     +  11,-  11
     +  11,-  11     +  10,-  32     +  12,-  11     +  11,-  10
     +  11,-  11     +  11,-  11     +  11,-  10     +  11,-  11
     +  11,-  11     +  11,- 105     +  89,-  88     +  11,-  33
     +  11,-  31     +  12,-  32     +  11,-  32     +  12,-  11
     +  11,-  10     +  11,-  32     +  12,-  10     +  11,-  11
     +  11,-  11     +  11,-  10     +  11,-  11     +  11,-  31
     +  12,-  32     +  12,-  10     +  11,-  33     +  11,-  11
     +  10,-  11     +  11,-  11     +  11,-  11     +  10,-  11
     +  11,-  11     +  11,-  31     +  12,-  33     +  11,-  32
     +  11,-  31     +  12,-  32     +  12,-  32     +  11,-  33
     +  11,-  31     +  12,-  11     +  11,-  10     +  11,-  11
     +  11,-  11     +  11,-  10     +  11,-  11     +  11,-  11
     +  11,-  10     +  11,-  11     +  11,-  32     +  11,-  33
     +  11,-  11     +  11,-  10     +  11,-  11     +  11,-  11
     +  11,-  10     +  11,-  11     +  11,-  11     +  11,-  10
     +  11,-  11     +  11,-  11     +  11,-  10     +  11,-  11
     +  11,-  11     +  11,-  10     +  11,-  32     +  12,-  10
     +  11,-  11     +  11,-  11     +  11,-  10     +  11,-  11
     +  11,-  11     +  11,-  10     +  11,-  11     +  11,-  32
     +  11,-  11     +  11,-  11     +  11,-  11     +  10,-  11
     +  11,-  11     +  11,-  11     +  10,-  11     +  11
Raw result in microseconds - with leading gap
rawData[296]: 
     -1828850
     +4450,-4400     + 550,-1600     + 550,-1600     + 550,-1650
     + 500,-1650     + 550,- 550     + 500,- 600     + 500,-1650
     + 550,- 550     + 550,- 500     + 550,- 550     + 550,- 550
     + 550,- 500     + 550,-1650     + 550,-1600     + 550,- 550
     + 500,-1650     + 550,- 550     + 500,- 600     + 500,- 550
     + 550,- 550     + 500,- 600     + 500,- 550     + 550,-1650
     + 500,-1650     + 550,-1600     + 550,-1600     + 550,-1650
     + 550,-1650     + 500,-1650     + 550,-1600     + 550,- 550
     + 550,- 550     + 500,- 600     + 500,- 550     + 550,- 550
     + 500,- 600     + 500,- 550     + 550,- 550     + 500,- 600
     + 500,-1650     + 500,-1650     + 550,- 550     + 500,- 600
     + 500,- 550     + 550,- 550     + 550,- 550     + 500,- 600
     + 500,- 550     + 550,- 550     + 500,- 550     + 550,- 550
     + 550,- 550     + 500,- 550     + 550,- 550     + 550,- 550
     + 550,-1600     + 550,- 550     + 500,- 600     + 500,- 550
     + 550,- 550     + 550,- 550     + 500,- 550     + 550,- 550
     + 550,- 550     + 500,-1600     + 600,- 550     + 550,- 500
     + 550,- 550     + 550,- 550     + 550,- 500     + 550,- 550
     + 550,- 550     + 550,-5250     +4450,-4400     + 550,-1650
     + 550,-1550     + 600,-1600     + 550,-1600     + 600,- 550
     + 550,- 500     + 550,-1600     + 600,- 500     + 550,- 550
     + 550,- 550     + 550,- 500     + 550,- 550     + 550,-1550
     + 600,-1600     + 600,- 500     + 550,-1650     + 550,- 550
     + 500,- 550     + 550,- 550     + 550,- 550     + 500,- 550
     + 550,- 550     + 550,-1550     + 600,-1650     + 550,-1600
     + 550,-1550     + 600,-1600     + 600,-1600     + 550,-1650
     + 550,-1550     + 600,- 550     + 550,- 500     + 550,- 550
     + 550,- 550     + 550,- 500     + 550,- 550     + 550,- 550
     + 550,- 500     + 550,- 550     + 550,-1600     + 550,-1650
     + 550,- 550     + 550,- 500     + 550,- 550     + 550,- 550
     + 550,- 500     + 550,- 550     + 550,- 550     + 550,- 500
     + 550,- 550     + 550,- 550     + 550,- 500     + 550,- 550
     + 550,- 550     + 550,- 500     + 550,-1600     + 600,- 500
     + 550,- 550     + 550,- 550     + 550,- 500     + 550,- 550
     + 550,- 550     + 550,- 500     + 550,- 550     + 550,-1600
     + 550,- 550     + 550,- 550     + 550,- 550     + 500,- 550
     + 550,- 550     + 550,- 550     + 500,- 550     + 550

Result as internal ticks (50 us) array - compensated with MARK_EXCESS_MICROS=20
uint8_t rawTicks[295] = {89,88, 11,32, 11,32, 11,33, 10,33, 11,11, 10,12, 10,33, 11,11, 11,10, 11,11, 11,11, 11,10, 11,33, 11,32, 11,11, 10,33, 11,11, 10,12, 10,11, 11,11, 10,12, 10,11, 11,33, 10,33, 11,32, 11,32, 11,33, 11,33, 10,33, 11,32, 11,11, 11,11, 10,12, 10,11, 11,11, 10,12, 10,11, 11,11, 10,12, 10,33, 10,33, 11,11, 10,12, 10,11, 11,11, 11,11, 10,12, 10,11, 11,11, 10,11, 11,11, 11,11, 10,11, 11,11, 11,11, 11,32, 11,11, 10,12, 10,11, 11,11, 11,11, 10,11, 11,11, 11,11, 10,32, 12,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,105, 89,88, 11,33, 11,31, 12,32, 11,32, 12,11, 11,10, 11,32, 12,10, 11,11, 11,11, 11,10, 11,11, 11,31, 12,32, 12,10, 11,33, 11,11, 10,11, 11,11, 11,11, 10,11, 11,11, 11,31, 12,33, 11,32, 11,31, 12,32, 12,32, 11,33, 11,31, 12,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,32, 11,33, 11,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,10, 11,32, 12,10, 11,11, 11,11, 11,10, 11,11, 11,11, 11,10, 11,11, 11,32, 11,11, 11,11, 11,11, 10,11, 11,11, 11,11, 10,11, 11};  // Protocol=UNKNOWN Hash=0xEF9393F4 148 bits received

Result as microseconds array - compensated with MARK_EXCESS_MICROS=20
uint16_t rawData[295] = {4430,4420, 530,1620, 530,1620, 530,1670, 480,1670, 530,570, 480,620, 480,1670, 530,570, 530,520, 530,570, 530,570, 530,520, 530,1670, 530,1620, 530,570, 480,1670, 530,570, 480,620, 480,570, 530,570, 480,620, 480,570, 530,1670, 480,1670, 530,1620, 530,1620, 530,1670, 530,1670, 480,1670, 530,1620, 530,570, 530,570, 480,620, 480,570, 530,570, 480,620, 480,570, 530,570, 480,620, 480,1670, 480,1670, 530,570, 480,620, 480,570, 530,570, 530,570, 480,620, 480,570, 530,570, 480,570, 530,570, 530,570, 480,570, 530,570, 530,570, 530,1620, 530,570, 480,620, 480,570, 530,570, 530,570, 480,570, 530,570, 530,570, 480,1620, 580,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,5270, 4430,4420, 530,1670, 530,1570, 580,1620, 530,1620, 580,570, 530,520, 530,1620, 580,520, 530,570, 530,570, 530,520, 530,570, 530,1570, 580,1620, 580,520, 530,1670, 530,570, 480,570, 530,570, 530,570, 480,570, 530,570, 530,1570, 580,1670, 530,1620, 530,1570, 580,1620, 580,1620, 530,1670, 530,1570, 580,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,1620, 530,1670, 530,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,520, 530,1620, 580,520, 530,570, 530,570, 530,520, 530,570, 530,570, 530,520, 530,570, 530,1620, 530,570, 530,570, 530,570, 480,570, 530,570, 530,570, 480,570, 530};  // Protocol=UNKNOWN Hash=0xEF9393F4 148 bits received

Pronto Hex as string
char prontoData[] = "0000 006D 0094 0000 00AC 00A8 0016 003D 0016 003D 0016 003F 0014 003F 0016 0014 0014 0016 0014 003F 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 003F 0016 003D 0016 0014 0014 003F 0016 0014 0014 0016 0014 0014 0016 0014 0014 0016 0014 0014 0016 003F 0014 003F 0016 003D 0016 003D 0016 003F 0016 003F 0014 003F 0016 003D 0016 0014 0016 0014 0014 0016 0014 0014 0016 0014 0014 0016 0014 0014 0016 0014 0014 0016 0014 003F 0014 003F 0016 0014 0014 0016 0014 0014 0016 0014 0016 0014 0014 0016 0014 0014 0016 0014 0014 0014 0016 0014 0016 0014 0014 0014 0016 0014 0016 0014 0016 003D 0016 0014 0014 0016 0014 0014 0016 0014 0016 0014 0014 0014 0016 0014 0016 0014 0014 003D 0018 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 00C9 00AC 00A8 0016 003F 0016 003B 0018 003D 0016 003D 0018 0014 0016 0012 0016 003D 0018 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 003B 0018 003D 0018 0012 0016 003F 0016 0014 0014 0014 0016 0014 0016 0014 0014 0014 0016 0014 0016 003B 0018 003F 0016 003D 0016 003B 0018 003D 0018 003D 0016 003F 0016 003B 0018 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 003D 0016 003F 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 003D 0018 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 0014 0016 0012 0016 0014 0016 003D 0016 0014 0016 0014 0016 0014 0014 0014 0016 0014 0016 0014 0014 0014 0016 06C3 ";
```

I can control the air conditioner with using pronto information.

**Comment by ArminJo** [comment]
Thanks.

> I could but does this mean that you don't want to do?

I dont want to have the effort of packaging and testing it to be honest, but I am not so reluctant anymore.

**Comment by asukiaaa** [comment]
Thank you for the comment.

> but I am not so reluctant anymore.

Can I think that you accept my request?

If yes, could you share the way to reproduce the error of the test.
I build for uno with enabling DEBUG flag on platform io but it was succeeded.

```
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = IRremote
build_flags =
  -DEBUG
```

```
pio run -t clean -e uno && pio run -e uno
```

```
================================ [SUCCESS] Took 1.77 seconds ================================

Environment    Status    Duration
-------------  --------  ------------
uno            SUCCESS   00:00:01.771
```

**Comment by ArminJo** [comment]
I am a bit lost 😞.
What is exact the problem you want to solve?

**Comment by asukiaaa** [comment]
Thank you for updating main branch.
I updated this pull request.

I want to call `RAW_BUFFER_LENGTH` by setting before `IRremote.h`.
```cpp
#define RAW_BUFFER_LENGTH 400
#include <IRremote.h>
```

**Comment by ArminJo** [comment]
Including IRremote.h is deprecated!

**Comment by asukiaaa** [comment]
Thank you for checking.
My code used `IRremote.hpp` and it works as I expect.

```cpp
#define RAW_BUFFER_LENGTH 400
#include <IRremote.hpp>
```

**Comment by ArminJo** [comment]
If iI merge your changes what is about other users using other decoders?
Does it work for them?

**Comment by asukiaaa** [comment]
I think that it is role of tests.
I can say that the code works on my environment.

By this change, it is no necessary to set `RAW_BUFFER_LENGTH` as global flag.

My environment
- Editor: PlatformIO
- Device: ESP32
- Remote controller: Toshiba WH-D6B

**Comment by ArminJo** [comment]
But you see that the tests were not succesful?

**Comment by asukiaaa** [comment]
Yes I see that tests were failed but I cannot reproduce that on my PC.
Can I see more log?

**Comment by ArminJo** [comment]
> Can I see more log?

Which more logs??? MicroGirs example failed!

**Comment by asukiaaa** [comment]
Thank you for updating master branch.
I update PR.

**Comment by ArminJo** [comment]
Thanks 🥇

**Comment by asukiaaa** [comment]
@ArminJo 
When will you release version 3.5.0?
I want to use and introduce it.
Thank you.

**Comment by ArminJo** [comment]
Dont know, if it is stable...
Why not just import the version manually?

**Comment by asukiaaa** [comment]
I see but current version also has trouble for long buffer length.
What does block releasing now?

> Why not just import the version manually?

I want to introduce the way to copy signal of some air conditioner  for beginners.
I think that it is hard for beginners to import latest version without using library manager.

**Comment by ArminJo** [comment]
> I see but current version also has trouble for long buffer length.
> What does block releasing now?

Normally one ore two weeks without a commit is the criteria for being stable.

> I want to introduce the way to copy signal of some air conditioner for beginners.
> I think that it is hard for beginners to import latest version without using library manager.

I agree, and thanks for doing it!

**Comment by asukiaaa** [comment]
> Normally one ore two weeks without a commit is the criteria for being stable.

I see, thank you for sharing your plan.

**Comment by ArminJo** [comment]
Just released 😀

**Comment by asukiaaa** [comment]
Thanks :)

**Comment by asukiaaa** [comment]
I wrote an article on my blog about copying signal of a remote controller of air conditioner. (in Japanese.)
Thank you for updating and maintaining this library.
https://asukiaaa.blogspot.com/2021/12/copy-and-send-ir-signal-by-esp32-arduino.html

**Pull request merged**
