### PR TITLE
Add espressif platforms to library.json

### LINKED ISSUE #846: PlatformIO (strict) Dependency Finder thinks library is not compatible
### Board
* [x] ESP32 board
* [x] probably also ESP8266

### IDE
* [x] PlatformIO IDE

### Protocol
irrelevant

### Version
* [x] Yes I use the [latest repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) and verified this!

### Current behavior
In PlatformIO I use a strict library dependency finder, because I want PIO to check whether librarys are compatible with framework **and the device platform**.
Here is the stripped down version of my platformio.ini:
```
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep+
lib_compat_mode = strict
lib_deps =
  IRremote=https://github.com/Arduino-IRremote/Arduino-IRremote#master
```

When compiling with strict compat mode PIO (only in verbose mode) says this during LDF finding:
```
Platform incompatible library C:\Users\User\Documents\GitHub\Project\.pio\libdeps\esp32dev\IRremote
More details about "Library Compatibility Mode": https://docs.platformio.org/page/librarymanager/ldf.html#ldf-compat-mode
```

### Expected behavior
As this library says it supports esp32, it should also advertise this to PlatformIO and thus compile without any problem

### Additional context
My guess is that in `library.json` the field platforms must be extended to also advertise `espressif32`.
While already at it, would be a good time to also add `espressif8288`.

### PR DESCRIPTION
**Pull request by programminghoch10**
fixes #846

### CODE REVIEW

**Comment by ArminJo** [comment]
Can you please add all platforms from the library.properties to to the library.json file?
I like to have only one commit for all 😀 .

**Comment by programminghoch10** [comment]
I have added the remaining platforms from library.properties.
I did not find the platform for `mbed`.
Architecture `stm32` is ambiguous, I have added both available `ststm32` and `ststm8` for 32bit and 8bit uC accordingly. I guess this includes architecture `stm32f1`.

**Comment by ArminJo** [comment]
Thanks, but I doubt ststm8 is right. I fear that the RogerClark kernel for stm32f1 is missing in the PlatformIO list like mbed.
So please remove ststm8 and rebase your repo, then I can merge it.
Alternatively (what I would prefer) I can include it im my next commit mentioning you as a collaborator.

**Comment by programminghoch10** [comment]
Sure do that, add me as co-author

**Comment by programminghoch10** [comment]
Quick info: the way you commited that, I'm not officially listed as contributor.
I mean its not a big thing, I'd just like to be listed :)
FYI heres how to add coauthors to a commit: https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors
or say that another person authored this commit and you just committed it: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt
Well anyways, I'd like to be an official contributer, but i hope I'll get that chance again soon. :)

**Comment by ArminJo** [comment]
Thanks I am still learning, but without your email I can not add you 😞

**Comment by programminghoch10** [comment]
Sure no problem!
You can get the commit email from anyone by executing 
```
$ git log -1
commit (...) (HEAD -> main, origin/main, origin/HEAD)
Author: programminghoch10 <16062290+programminghoch10@users.noreply.github.com>
Date:   Mon Apr 12 11:51:52 2021 +0200

    small changes

```

**Pull request closed without merging**
